Js lesson 2
blank-4/exercises-delphinegrace pull request #11
Opened 2018-11-26 15:55 UTC by delphinegrace

2018-11-26 16:05 UTC, Neilsafraoui requested changes
la syntaxe est OK, mais l'énoncé n'est pas suivi précisément

2018-11-26 16:05 UTC, Neilsafraoui commented on javascript/lesson2/exercise1/main.js
> +  } else if (heure >= 20){
relis l'énoncé plus précisément 
(c'est pour cela que je conseille de garder l'énoncé en commentaire en haut du code)
je cite "Si la valeur de heure est inférieure a 10"

2018-11-26 16:05 UTC, Neilsafraoui commented on javascript/lesson2/exercise1/main.js
> +  } else if (heure >= 20){
de même pour l'énoncé
"sinon, si la valeur de heure est inférieure a 20"
de plus, on utilisera les operations "inférieur ou égal" (soit <=) SI l'énoncé le précise, ici c'est pas précisé inférieur ou égal, on va donc utiliser le strictement inférieur

2018-11-26 16:05 UTC, Neilsafraoui commented on javascript/lesson2/exercise1/main.js
> +  } else if( heure< 20){
l'énoncé indique "SINON" et non pas "SINON SI", il faut utiliser un "else" pour le dernier test

2018-11-26 16:46 UTC, yohanngab commented on javascript/lesson2/exercise2/main.js
> +    console.log( "je décompte de deux en deux" + i)
Il manque l'accolade fermante!

2018-11-26 16:46 UTC, yohanngab commented on javascript/lesson2/exercise2/main.js
> +
saut de ligne en trop

2018-11-26 16:46 UTC, yohanngab commented on javascript/lesson2/exercise2/main.js
> +for ( var i = 0 ; i < 100 ; i++ ) {
espace en trop avant la declaration de ta variable

2018-11-26 16:46 UTC, yohanngab commented on javascript/lesson2/exercise2/main.js
> +for(var i = 0 ; i< 100 ; i+2);{
i+2 ne va pas fonctionner

2018-11-26 16:46 UTC, yohanngab commented on javascript/lesson2/exercise2/main.js
> +for(var i = 100 ; i> 100 ; i+2);{
i+2 ne va pas fonctionner

2018-11-27 09:56 UTC, Neilsafraoui approved these changes
OK
mais aligne bien ton code, i mean, garde l'uniformité

2018-11-27 10:33 UTC, Neilsafraoui approved these changes
OK pour la logique des modulos, on aurait pu également afficher le reste des nombres (non multiples de 5 ou 7) dans une condition else

2018-12-10 09:54 UTC, merged

2018-12-10 09:54 UTC, FaXaq commented
Je merge, n'hésite pas à regarder la correction