Java lesson 5
blank-4/exercises-delphinegrace pull request #14
Opened 2018-12-07 14:54 UTC by delphinegrace

2018-12-07 15:06 UTC, Neilsafraoui requested changes
voir commentaires
c'est pas mal mais il manque le changement d'image via un bouton

2018-12-07 15:06 UTC, Neilsafraoui commented on javascript/lesson5/exercise3/main.js
> +var str = document.getElementById("monTableau"); str.innerHTML = "lorem ipsum";
Une instruction par ligne :)
et cette ligne renvoie une erreur, car il n'y a pas (dans le html) d'élément avec l'id ="monTableau"

2018-12-07 15:06 UTC, Neilsafraoui commented on javascript/lesson5/exercise3/main.js
> +function img() {
la fonction est bien dans la logique de random
mais il faut l'appeler quelque part pour effectuer le changement de photo (normalement sur le bouton dans le HTML)

2018-12-07 15:06 UTC, Neilsafraoui commented on javascript/lesson5/exercise3/index.html
> +                <input class="favorite styled"
juste pour info, <input type="button"> est rarement utilisé... (il me semble)
on utilise <input type="submit"> pour envoyer un formulaire ou <button>texte</button> pour une action déterminée

2018-12-10 09:58 UTC, FaXaq commented
Je merge, n'hésite pas à regarder la correction

2018-12-10 09:58 UTC, merged