exo1
blank-4/exercises-delphinegrace pull request #3
Opened 2018-11-07 15:20 UTC by delphinegrace

2018-11-07 15:22 UTC, yohanngab requested changes

2018-11-07 15:22 UTC, yohanngab commented on html/lesson3/exercise1/index.html
> +<!Doctype html>
le doctype doit être en majuscule

2018-11-07 15:22 UTC, yohanngab commented on html/lesson3/exercise1/index.html
> +        <title><h1>'amour Parisien</h1></title>
il ne peut pas y avoir de h1 dans le title! Uniquement dans le contenu

2018-11-07 15:22 UTC, yohanngab commented on html/lesson3/exercise1/index.html
> +        <p id="Amour Solitaire">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, quibusdam! Rerum, facilis facere corporis deleniti, dolorem magnam reprehenderit explicabo omnis aliq
Les id doivent s'écrire en un seul mot : "amour-solitaire"

Il faut en mettre sur chaque paragraphe

2018-11-07 15:22 UTC, yohanngab commented on html/lesson3/exercise1/index.html
> +
sauts de ligne inutiles

2018-11-07 15:33 UTC, yohanngab requested changes

2018-11-07 15:33 UTC, yohanngab commented on html/lesson3/exercise1/index.html
> +         <p id="Relation-Epistolaire 2.0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore delectus explicabo ipsam maxime provident ut dolorum voluptatem quia perferendis distinctio?
2.0 sera considéré comme un deuxième id, il faut mettre un tiret et éviter les majuscules et points autant que possible :)

2018-11-07 15:59 UTC, yohanngab commented on html/lesson3/exercise2/index.html
> +              <li>
Mettre les éléments de liste en ligne :
<li><a href="">blablabla</a></li>

2018-11-07 15:59 UTC, yohanngab commented on html/lesson3/exercise2/index.html
> +         <p id="Grand-amour-et-Perdition">Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde molestiae aperiam fugiat velit totam consequuntur dolore architecto sunt aliquam nihil exceptur
Eviter les majuscules !

2018-11-08 15:14 UTC, FaXaq commented
Je merge, n'hésite pas à regarder la correction dans le cloud

2018-11-08 15:14 UTC, merged